FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y openjdk-8-jdk wget
RUN mkdir /opt/tomcat
#COPY apache-tomcat-8.5.37.tar.gz
#RUN cd /tmp && tar xvfz apache-tomcat-8.5.37.tar.gz
#RUN mv /tmp/apache-tomcat-8.5.37/* /opt/tomcat 
#RUN rm /tmp/apache-tomcat-8.5.37.tar.gz
ADD tomcat-8.5.37.tar.gz /tmp
RUN mv /tmp/apache-tomcat-8.5.37/* /opt/tomcat
COPY myapp.war /opt/tomcat/webapps
EXPOSE 8080
ENTRYPOINT ["/opt/tomcat/bin/catalina.sh","run"] ##JSON format
#ENTRYPOINT /opt/tomcat/bin/catalina.sh run ##Shell format
